version: '3.4'

services:
  sqlserver:
    hostname: 'sqlserver'
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: 'sqlserver'
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: SqlServer_Password    

  ogc-tests:
    hostname: 'ogcciteapp'
    image: ogccite/ets-ogcapi-features10
    container_name: 'ogcciteapp'
    ports:
      - 8082:8080        

  samplewebapplication:
    hostname: 'webapp'
    container_name: 'webapp'    
    build:
      context: .
      dockerfile: SampleWebApplication/Dockerfile
    ports:
      - 80:8080
      - 443:8081     

networks:
  ogc-api:    
    driver: bridge