<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Description>Schemas provider for OGC API Features Standard implementation</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OgcApi.Net\OgcApi.Net.csproj" />
  </ItemGroup>

</Project>
